{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: hipstershop
spec:
  type: {{ .Values.service.type }}
  selector:
    app: adservice
    project: hipstershop
    tier: app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
{{- end }}
