apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: checkoutservice
      project: hipstershop
      tier: app
  template:
    metadata:
      labels:
        app: checkoutservice
        project: hipstershop
        tier: app
    spec:
      serviceAccountName: my-service-account 
      containers:
        - name: checkout
          image: "registry.gitlab.com/gyenoch1/microservice/checkoutservice:{{ .Values.deployment.imageVersion }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 5050
          envFrom:
          - configMapRef:
              name: checkoutservice
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      imagePullSecrets:
        - name: my-registry-secret
