apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Or "elb", depending on preference
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
    project: hipstershop
    tier: web
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 8080 #container-port
